# Generated by Django 3.2.9 on 2021-12-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
