# Generated by Django 3.2.9 on 2021-12-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20211202_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='by',
            field=models.TextField(),
        ),
    ]
